# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6789e3b2a73b7341b781479d25321bf26601b897efb89380a4eb143c7a02a570ef14a8213182e2c85a55e734ef8bf1ca3915cd25179dea9ba57373df023f5f6

test:
  secret_key_base: 419330bb77a9cd5ba8a14b56c4135b04e2c90f703910ece9cb7fa31d7234d07fd1e82eb7653e8d6d4119392ec55612e698a1ee28a9db985d6900692da97126f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
